---
- name: apt update
  apt:
    update_cache: yes

- name: install pip
  apt:
   name: python3-pip
   state: present

- name: install packages
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
    state: present

- name: apt update
  apt:
    update_cache: yes
