---
- name: log on ECR
  shell: "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{ docker_registry }}"

- name: build and push docker image
  docker_image:
    build:
      path: /home/ubuntu/webapp
    name: "{{ docker_registry }}"
    tag: "{{ tag | default('latest') }}"
    push: yes
    source: build
