# ---
- name: Webapp playbook
  hosts: prod
  tasks:
  
    - name: Install package https 
      apt:
       name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
       state: present
                
    - name: Install key GPG for docker
      shell:
       cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    - name: add docker repo
      shell:
       cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Apt update
      apt:
       update_cache: yes

    - name: Install docker
      apt:
       name: docker-ce
       state: present
    
    - name: add user ubuntu to group docker
      shell:
       cmd: usermod -a -G docker ubuntu 
  
  # ---