---
- hosts: db
  roles:
    - role: geerlingguy.mysql
      become: yes
  vars:
    mysql_root_password: root
    mysql_databases:
      - name: webapp
    mysql_users:
      - name: root
#        host: "localhost"
        password: root
        priv: "*.*:ALL"
